### PR TITLE
Added basic structure to material class

### PR DESCRIPTION
**Pull request by wzheng21**
Added basic functionalities with TODO.
The scattering eigen spectrum decomposition has been added.

I was not sure about how I could do what you suggested about rebasing, so @jsrehak, I will leave this as a PR but you could also lead me to doing what you suggested instead of PR.

### CODE REVIEW

**Comment by jsrehak** [comment]
@weixiong-zheng-berkeley is this ready to merge? If yes, it adds a new feature, so we should merge like normal and explain what is added in the merge commit message.

**Comment by jsrehak** [comment]
@weixiong-zheng-berkeley please update this pull request to target the `mat-io` branch.

**Comment by wzheng21** [comment]
will do thnx

**Comment by wzheng21** [comment]
@jsrehak Updated and resolved conflicts. You know how to fix the fact that I cannot merge PRs?

**Comment by jsrehak** [comment]
All changes have already been committed in the `mat-io` branch.

**Pull request closed without merging**
